[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/about/"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/services/"
  to = "/services"
  status = 301
  force = true

[[redirects]]
  from = "/booking/"
  to = "/booking"
  status = 301
  force = true

[[redirects]]
  from = "/faq/"
  to = "/faq"
  status = 301
  force = true
